### ISSUE TITLE
[URGENT] Test hosting environment on kratie

### ISSUE THREAD

**Issue by bbalet** [pnc-virtual-company/2018-inventory#60]
Use the spreadsheet _Hosting on Kratie_ in Google Drive folder 00-Common:

- [x] Test that you can access to phpMyAdmin with your credentials: http://kratie.pnc.lan/phpmyadmin/
- [x] Test that you can connect to the server with FileZilla.
- [x] Try to upload your application (don't forget to setup database).

**Comment by huor-panha** [comment]
For Group C, We already uploaded the application into the server and the database already set up but we see only the moving circle on the screen.

**Comment by bbalet** [comment]
This was solved this afternoon, see: http://kratie.pnc.lan/2018vc2gc/
